//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int NominaID { get; set; }
        public Nullable<int> EmpleadoID { get; set; }
        public Nullable<int> DiasTrabajados { get; set; }
        public Nullable<int> SueldoPorDia { get; set; }
        public Nullable<int> SueldoQuincenal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
